### ISSUE TITLE
Have you got Arcade , NIghtclub , any other Safe Globals?

### ISSUE THREAD

**Issue by thizsam** [dr-NHA/GtaV_2#1]
Have you got Arcade , NIghtclub , any other Safe Globals? thank you in advance

**Comment by dr-NHA** [comment]
Whats Listed Is What Ive Currently Got,
Submissions Of Globals And Included Script Name And Function Of What Houses The Said Global Would Be Amazing As The Dumped Globals Here Are Dumped Via My Global Offset Scanner Project:
[Global Offset Scanner / C Source Scanner](https://github.com/dr-NHA/GTAV-C-Source-Scanner)
